// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: time_mat.proto

#ifndef PROTOBUF_INCLUDED_time_5fmat_2eproto
#define PROTOBUF_INCLUDED_time_5fmat_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_time_5fmat_2eproto 

namespace protobuf_time_5fmat_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_time_5fmat_2eproto
namespace robotics {
namespace matlab {
class TimeMat;
class TimeMatDefaultTypeInternal;
extern TimeMatDefaultTypeInternal _TimeMat_default_instance_;
}  // namespace matlab
}  // namespace robotics
namespace google {
namespace protobuf {
template<> ::robotics::matlab::TimeMat* Arena::CreateMaybeMessage<::robotics::matlab::TimeMat>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace robotics {
namespace matlab {

// ===================================================================

class TimeMat : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:robotics.matlab.TimeMat) */ {
 public:
  TimeMat();
  virtual ~TimeMat();

  TimeMat(const TimeMat& from);

  inline TimeMat& operator=(const TimeMat& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TimeMat(TimeMat&& from) noexcept
    : TimeMat() {
    *this = ::std::move(from);
  }

  inline TimeMat& operator=(TimeMat&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TimeMat& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TimeMat* internal_default_instance() {
    return reinterpret_cast<const TimeMat*>(
               &_TimeMat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(TimeMat* other);
  friend void swap(TimeMat& a, TimeMat& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TimeMat* New() const final {
    return CreateMaybeMessage<TimeMat>(NULL);
  }

  TimeMat* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TimeMat>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TimeMat& from);
  void MergeFrom(const TimeMat& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TimeMat* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 m_sec = 1;
  bool has_m_sec() const;
  void clear_m_sec();
  static const int kMSecFieldNumber = 1;
  ::google::protobuf::int32 m_sec() const;
  void set_m_sec(::google::protobuf::int32 value);

  // required int32 m_nsec = 2;
  bool has_m_nsec() const;
  void clear_m_nsec();
  static const int kMNsecFieldNumber = 2;
  ::google::protobuf::int32 m_nsec() const;
  void set_m_nsec(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:robotics.matlab.TimeMat)
 private:
  void set_has_m_sec();
  void clear_has_m_sec();
  void set_has_m_nsec();
  void clear_has_m_nsec();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int32 m_sec_;
  ::google::protobuf::int32 m_nsec_;
  friend struct ::protobuf_time_5fmat_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TimeMat

// required int32 m_sec = 1;
inline bool TimeMat::has_m_sec() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TimeMat::set_has_m_sec() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TimeMat::clear_has_m_sec() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TimeMat::clear_m_sec() {
  m_sec_ = 0;
  clear_has_m_sec();
}
inline ::google::protobuf::int32 TimeMat::m_sec() const {
  // @@protoc_insertion_point(field_get:robotics.matlab.TimeMat.m_sec)
  return m_sec_;
}
inline void TimeMat::set_m_sec(::google::protobuf::int32 value) {
  set_has_m_sec();
  m_sec_ = value;
  // @@protoc_insertion_point(field_set:robotics.matlab.TimeMat.m_sec)
}

// required int32 m_nsec = 2;
inline bool TimeMat::has_m_nsec() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TimeMat::set_has_m_nsec() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TimeMat::clear_has_m_nsec() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TimeMat::clear_m_nsec() {
  m_nsec_ = 0;
  clear_has_m_nsec();
}
inline ::google::protobuf::int32 TimeMat::m_nsec() const {
  // @@protoc_insertion_point(field_get:robotics.matlab.TimeMat.m_nsec)
  return m_nsec_;
}
inline void TimeMat::set_m_nsec(::google::protobuf::int32 value) {
  set_has_m_nsec();
  m_nsec_ = value;
  // @@protoc_insertion_point(field_set:robotics.matlab.TimeMat.m_nsec)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace matlab
}  // namespace robotics

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_time_5fmat_2eproto
