// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: time_mat.proto

#include "time_mat.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace robotics {
namespace matlab {
class TimeMatDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TimeMat>
      _instance;
} _TimeMat_default_instance_;
}  // namespace matlab
}  // namespace robotics
namespace protobuf_time_5fmat_2eproto {
static void InitDefaultsTimeMat() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::robotics::matlab::_TimeMat_default_instance_;
    new (ptr) ::robotics::matlab::TimeMat();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::robotics::matlab::TimeMat::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_TimeMat =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsTimeMat}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_TimeMat.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::robotics::matlab::TimeMat, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::robotics::matlab::TimeMat, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::robotics::matlab::TimeMat, m_sec_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::robotics::matlab::TimeMat, m_nsec_),
  0,
  1,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::robotics::matlab::TimeMat)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::robotics::matlab::_TimeMat_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "time_mat.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\016time_mat.proto\022\017robotics.matlab\"(\n\007Tim"
      "eMat\022\r\n\005m_sec\030\001 \002(\005\022\016\n\006m_nsec\030\002 \002(\005"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 75);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "time_mat.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_time_5fmat_2eproto
namespace robotics {
namespace matlab {

// ===================================================================

void TimeMat::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TimeMat::kMSecFieldNumber;
const int TimeMat::kMNsecFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TimeMat::TimeMat()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_time_5fmat_2eproto::scc_info_TimeMat.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:robotics.matlab.TimeMat)
}
TimeMat::TimeMat(const TimeMat& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&m_sec_, &from.m_sec_,
    static_cast<size_t>(reinterpret_cast<char*>(&m_nsec_) -
    reinterpret_cast<char*>(&m_sec_)) + sizeof(m_nsec_));
  // @@protoc_insertion_point(copy_constructor:robotics.matlab.TimeMat)
}

void TimeMat::SharedCtor() {
  ::memset(&m_sec_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&m_nsec_) -
      reinterpret_cast<char*>(&m_sec_)) + sizeof(m_nsec_));
}

TimeMat::~TimeMat() {
  // @@protoc_insertion_point(destructor:robotics.matlab.TimeMat)
  SharedDtor();
}

void TimeMat::SharedDtor() {
}

void TimeMat::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* TimeMat::descriptor() {
  ::protobuf_time_5fmat_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_time_5fmat_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const TimeMat& TimeMat::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_time_5fmat_2eproto::scc_info_TimeMat.base);
  return *internal_default_instance();
}


void TimeMat::Clear() {
// @@protoc_insertion_point(message_clear_start:robotics.matlab.TimeMat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    ::memset(&m_sec_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&m_nsec_) -
        reinterpret_cast<char*>(&m_sec_)) + sizeof(m_nsec_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool TimeMat::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:robotics.matlab.TimeMat)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 m_sec = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_m_sec();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &m_sec_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 m_nsec = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_m_nsec();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &m_nsec_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:robotics.matlab.TimeMat)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:robotics.matlab.TimeMat)
  return false;
#undef DO_
}

void TimeMat::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:robotics.matlab.TimeMat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 m_sec = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->m_sec(), output);
  }

  // required int32 m_nsec = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->m_nsec(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:robotics.matlab.TimeMat)
}

::google::protobuf::uint8* TimeMat::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:robotics.matlab.TimeMat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 m_sec = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->m_sec(), target);
  }

  // required int32 m_nsec = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->m_nsec(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:robotics.matlab.TimeMat)
  return target;
}

size_t TimeMat::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:robotics.matlab.TimeMat)
  size_t total_size = 0;

  if (has_m_sec()) {
    // required int32 m_sec = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->m_sec());
  }

  if (has_m_nsec()) {
    // required int32 m_nsec = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->m_nsec());
  }

  return total_size;
}
size_t TimeMat::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:robotics.matlab.TimeMat)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required int32 m_sec = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->m_sec());

    // required int32 m_nsec = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->m_nsec());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TimeMat::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:robotics.matlab.TimeMat)
  GOOGLE_DCHECK_NE(&from, this);
  const TimeMat* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TimeMat>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:robotics.matlab.TimeMat)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:robotics.matlab.TimeMat)
    MergeFrom(*source);
  }
}

void TimeMat::MergeFrom(const TimeMat& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:robotics.matlab.TimeMat)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      m_sec_ = from.m_sec_;
    }
    if (cached_has_bits & 0x00000002u) {
      m_nsec_ = from.m_nsec_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void TimeMat::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:robotics.matlab.TimeMat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TimeMat::CopyFrom(const TimeMat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:robotics.matlab.TimeMat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TimeMat::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void TimeMat::Swap(TimeMat* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TimeMat::InternalSwap(TimeMat* other) {
  using std::swap;
  swap(m_sec_, other->m_sec_);
  swap(m_nsec_, other->m_nsec_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata TimeMat::GetMetadata() const {
  protobuf_time_5fmat_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_time_5fmat_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace matlab
}  // namespace robotics
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::robotics::matlab::TimeMat* Arena::CreateMaybeMessage< ::robotics::matlab::TimeMat >(Arena* arena) {
  return Arena::CreateInternal< ::robotics::matlab::TimeMat >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
