// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector3d_mat.proto

#ifndef PROTOBUF_INCLUDED_vector3d_5fmat_2eproto
#define PROTOBUF_INCLUDED_vector3d_5fmat_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_vector3d_5fmat_2eproto 

namespace protobuf_vector3d_5fmat_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_vector3d_5fmat_2eproto
namespace robotics {
namespace matlab {
class Vector3dMat;
class Vector3dMatDefaultTypeInternal;
extern Vector3dMatDefaultTypeInternal _Vector3dMat_default_instance_;
}  // namespace matlab
}  // namespace robotics
namespace google {
namespace protobuf {
template<> ::robotics::matlab::Vector3dMat* Arena::CreateMaybeMessage<::robotics::matlab::Vector3dMat>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace robotics {
namespace matlab {

// ===================================================================

class Vector3dMat : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:robotics.matlab.Vector3dMat) */ {
 public:
  Vector3dMat();
  virtual ~Vector3dMat();

  Vector3dMat(const Vector3dMat& from);

  inline Vector3dMat& operator=(const Vector3dMat& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Vector3dMat(Vector3dMat&& from) noexcept
    : Vector3dMat() {
    *this = ::std::move(from);
  }

  inline Vector3dMat& operator=(Vector3dMat&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Vector3dMat& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Vector3dMat* internal_default_instance() {
    return reinterpret_cast<const Vector3dMat*>(
               &_Vector3dMat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Vector3dMat* other);
  friend void swap(Vector3dMat& a, Vector3dMat& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Vector3dMat* New() const final {
    return CreateMaybeMessage<Vector3dMat>(NULL);
  }

  Vector3dMat* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Vector3dMat>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Vector3dMat& from);
  void MergeFrom(const Vector3dMat& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector3dMat* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double m_x = 1;
  bool has_m_x() const;
  void clear_m_x();
  static const int kMXFieldNumber = 1;
  double m_x() const;
  void set_m_x(double value);

  // required double m_y = 2;
  bool has_m_y() const;
  void clear_m_y();
  static const int kMYFieldNumber = 2;
  double m_y() const;
  void set_m_y(double value);

  // required double m_z = 3;
  bool has_m_z() const;
  void clear_m_z();
  static const int kMZFieldNumber = 3;
  double m_z() const;
  void set_m_z(double value);

  // @@protoc_insertion_point(class_scope:robotics.matlab.Vector3dMat)
 private:
  void set_has_m_x();
  void clear_has_m_x();
  void set_has_m_y();
  void clear_has_m_y();
  void set_has_m_z();
  void clear_has_m_z();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  double m_x_;
  double m_y_;
  double m_z_;
  friend struct ::protobuf_vector3d_5fmat_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Vector3dMat

// required double m_x = 1;
inline bool Vector3dMat::has_m_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Vector3dMat::set_has_m_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Vector3dMat::clear_has_m_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Vector3dMat::clear_m_x() {
  m_x_ = 0;
  clear_has_m_x();
}
inline double Vector3dMat::m_x() const {
  // @@protoc_insertion_point(field_get:robotics.matlab.Vector3dMat.m_x)
  return m_x_;
}
inline void Vector3dMat::set_m_x(double value) {
  set_has_m_x();
  m_x_ = value;
  // @@protoc_insertion_point(field_set:robotics.matlab.Vector3dMat.m_x)
}

// required double m_y = 2;
inline bool Vector3dMat::has_m_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Vector3dMat::set_has_m_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Vector3dMat::clear_has_m_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Vector3dMat::clear_m_y() {
  m_y_ = 0;
  clear_has_m_y();
}
inline double Vector3dMat::m_y() const {
  // @@protoc_insertion_point(field_get:robotics.matlab.Vector3dMat.m_y)
  return m_y_;
}
inline void Vector3dMat::set_m_y(double value) {
  set_has_m_y();
  m_y_ = value;
  // @@protoc_insertion_point(field_set:robotics.matlab.Vector3dMat.m_y)
}

// required double m_z = 3;
inline bool Vector3dMat::has_m_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Vector3dMat::set_has_m_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Vector3dMat::clear_has_m_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Vector3dMat::clear_m_z() {
  m_z_ = 0;
  clear_has_m_z();
}
inline double Vector3dMat::m_z() const {
  // @@protoc_insertion_point(field_get:robotics.matlab.Vector3dMat.m_z)
  return m_z_;
}
inline void Vector3dMat::set_m_z(double value) {
  set_has_m_z();
  m_z_ = value;
  // @@protoc_insertion_point(field_set:robotics.matlab.Vector3dMat.m_z)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace matlab
}  // namespace robotics

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_vector3d_5fmat_2eproto
